Basic UI
benshidanny11/school_library pull request #4
Opened 2022-07-20 21:40 UTC by benshidanny11

# In this milestone I:
- Implemented basic UI (Command line interface)
- Created the app file that contains all create and list data features
- Created the main file that works as the entry file for the app.

2022-07-20 23:04 UTC, Mre55 requested changes
**Hi @benshidanny11,**

You have done a great job so far! 💪 👏 
You still need to work on a few issues before moving on to the next project, but you're almost there!

## To highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 

## Required Changes ♻️🛠️ 
_Check the comments under the review._

<img width="430" src="https://media1.giphy.com/media/oVjOd9TEZDmSTc4x37/giphy.gif"/>


## Optional suggestions 🟡 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-20 23:04 UTC, Mre55 commented on app.rb
> +  end
When listing all people the console order is not correct it consoles age to Name and vice versa.

<img width="746" alt="image" src="https://user-images.githubusercontent.com/34578631/180095770-bd048d9e-fe87-463a-8be6-0addc6067856.png">

2022-07-20 23:04 UTC, Mre55 commented on app.rb
> +  end
Kindly, fix creating teacher method it's crashing the app.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/34578631/180095913-b30da212-58ef-41f1-9d9a-5a681fee5185.png">

Here I attached the screenshot video where using the app and some of its features are crashing the app.

https://user-images.githubusercontent.com/34578631/180096683-38a88dba-f036-4fb3-95db-1cdd2b702ad6.mov

2022-07-20 23:04 UTC, Mre55 commented on app.rb
> +  end
Creating rental is also crashing the app. Kindly, this features.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/34578631/180096038-13448579-d4a0-430c-b638-6cf480465cf8.png">

2022-07-21 21:28 UTC, rloterh commented on app.rb
> +  end
This issue is well resolved! ✔️

2022-07-21 21:28 UTC, rloterh commented on app.rb
> +  end
This issue is well resolved! ✔️

2022-07-21 21:29 UTC, rloterh commented on app.rb
> +  end
This issue is well resolved! ✔️

2022-07-21 21:34 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Daniel,  

Your project is complete! There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉🌟 

## Highlights 👍
- Interactive console apps properly created

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-21 21:38 UTC, benshidanny11 commented
@rloterh Thanks for approving my project

2022-07-22 18:52 UTC, merged